### ISSUE TITLE
Be able to use all types in gsd_rdf

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/cmeutils#10]
Right now, `gsd_rdf` can either do 1 or 2 types, but it would be nice to also use all of the particles in calculating the RDF.  This would be especially useful when using it for coarse-grained systems.

For example, if you have a system of "A" and "B" beads, currently we could find the RDF for A-A, B-B or A-B correlations, but cannot find the RDF that accounts for all of them at once.

**Comment by jennyfothergill** [comment]
Agreed. I really like how you implemented it in `msd_from_gsd`

**Comment by gwenwhite** [comment]
So, just to be sure, are you thinking of an RDF code that calculates all atoms in the molecule at once(not just the selected A and B atoms)?
