### ISSUE TITLE
All-atom rdf slow

### ISSUE THREAD

**Issue by gwenwhite** [cmelab/cmeutils#12]
A system with 9,150 atoms takes a minute per snapshot, and Eric says it should be faster.

**Comment by jennyfothergill** [comment]
What parameters are you using? Are you setting rmax? Because if not, the default is to use half the box length: https://github.com/cmelab/cmeutils/pull/11#issuecomment-908441715
Either way, let's include a snippet of how you're using the function in this issue.

**Comment by jennyfothergill** [comment]
gwen was using r_max=6
