### ISSUE TITLE
Make gsd of a specified structure within a trajectory.

### ISSUE THREAD

**Issue by JimmyRushing** [cmelab/cmeutils#18]
Similar to the get_centers issue, it would be nice to provide smiles/exact indices for the structure that you are interested in and have a new gsd for that structure. For example, a function that takes an ITIC trajectory and the atom indices of the donor core, and returns a new trajectory that tracks the center of those atom indices. With that, we could investigate the msd,rdf etcetra of that particular structure.

**Comment by jennyfothergill** [comment]
I'm closing this issue because it is resolved using grits
